In [ ]:
class FinalExam:

  def __init__(self, name):
    self.__name = name
  
  def setName(self, name):
    self.__name = name
  
  def getName(self):
    return self.__name

  def __str__(self):
    return self.__name
  
  def printDetails(self):
    return f'I wish there were no finals'

###Write your code here
class Student(FinalExam):
  total=0
  def __init__(self,name,id,sub):
    super().__init__(name)
    self.id=id
    self.sub=sub
    Student.total+=1
    self.c=0
    print ('Question khub easy!!!')
  def __str__(self):
    st=f'Student name: {super().getName()} Id: {self.id} Department: {self.sub}'
    return st
  def printDetails(self):
    st='Yesss! Miltese code ta\nKintu pass korte hole final exam to ditei hobe!!\n'
    st+=f'Total number of Students: {Student.total}  '
    return st
  def __add__ (self,other):
    self.c+=1
    other.c+=1
    st=f'{self.getName()} and {other.getName()} are friends Now!\n'
    st+=f'{self.getName()} has total {self.c} friens now\n'
    st+=f'{other.getName()} has total {other.c} friens now\n  '
    return st
  def __sub__ (self,other):
    return f"{self.getName()} and {other.getName()} are enemies! "

t1 = Student('Andy','18101201', 'CSE')
print(t1)
print(t1.printDetails())
print("=================================") 
t2 = Student('George','19101311', 'CSE')
print(t2)
print(t2.printDetails())
print("=================================") 
t3 = Student('Mina', '19201421', 'BBA')
print(t3)
print(t3.printDetails())
print("=================================") 
t4 = Student('John', '18401221', 'BBA')
print("=================================") 
print(t1+t3)
print("=================================") 
print(t1+t2)
print("=================================") 
print(t2+t3)
print("=================================") 
print(t2-t4)

Question khub easy!!!
Student name: Andy Id: 18101201 Department: CSE
Yesss! Miltese code ta
Kintu pass korte hole final exam to ditei hobe!!
Total number of Students: 1
=================================
Question khub easy!!!
Student name: George Id: 19101311 Department: CSE
Yesss! Miltese code ta
Kintu pass korte hole final exam to ditei hobe!!
Total number of Students: 2
=================================
Question khub easy!!!
Student name: Mina Id: 19201421 Department: BBA
Yesss! Miltese code ta
Kintu pass korte hole final exam to ditei hobe!!
Total number of Students: 3
=================================
Question khub easy!!!
=================================
Andy and Mina are friends Now!
Andy has total 1 friens now
Mina has total 1 friens now

=================================
Andy and George are friends Now!
Andy has total 2 friens now
George has total 1 friens now

=================================
George and Mina are friends Now!
George has total 2 friens now
Mina has total 2 friens now

=================================
George and John are enemies!

In [5]:
3--4+2

9

In [6]:
class A:
    temp = -5
    def __init__(self):
        self.sum = 1
        self.y = 2
        self.y = self.temp - 3
        self.sum = A.temp + 2
        A.temp -= 2
    def methodA(self, m, n):
        x = 1
        A.temp += 1
        self.y = self.y + m + self.temp
        x = x + 1 + n
        self.sum = self.sum + x + self.y
        print(f"{x} {self.y} {self.sum}")
class B(A):
    x = -10
    def __init__(self, b = None):
        super().__init__()
        self.y = 3
        self.temp = -4
        self.sum = 1
        if b == None:
            self.y = self.temp + 2
            self.sum = 3 + self.temp + 2
            self.temp -= 2
        else:
            self.sum = b.sum
            B.x = b.x
    def methodA(self, m, n):
        x = 1
        self.temp += 2
        self.y = self.y + m + self.temp
        x = x + 6 + n
        super().methodA(x, m)
        self.sum = self.sum + x + self.y
        print(f"{x} {self.y} {self.sum}")
    def methodB(self, m, n):
        y = 3
        y = y + self.y
        B.x = self.y + 3 + self.temp
        self.methodA(B.x, y)
        self.sum = self.x + y + self.sum
        print(f"{B.x} {y} {self.sum}")
b1=B()
b2=B(b1)
b2.methodB(1,3)

4 14 19
13 14 46
2 6 54